### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by appworksco** [SSP6904/chipinCSS#1]
To see more of these settings, please see our documentation. Keep in mind that some of them require Javascript, so be sure to have JQuary installed!

**Comment by SSP6904** [comment]
Thank you for pointing that out. I will change that for you. Just to let you know, what we use to write our documentation site is on Codespaces for deployment and such, and it doesn't check for spelling for some reason. I will fix that later on.

**Comment by SSP6904** [comment]
We detected the typo on line 1. jQuery and JavaScript was spelled wrong. We will put that in the repo shortly. Please close this issue once the commit is pushed. If you see any typos missed or needs to be changed, please let me know. 🙂

```
To see more of these settings, please see our documentation. Keep in mind that some of them require JavaScript, so be sure to have jQuery installed!
```

**Comment by SSP6904** [comment]
See changes here: https://github.com/SSP6904/chipinCSS/commit/3574e832d359b04c8055ff358389417c956eeda0
